### ISSUE TITLE
Sakhi Phase 1 UAT Feedback

### ISSUE THREAD

**Issue by arjunk** [avniproject/SAKHI#17]
Reference 
Orginal Form requirement Sheet : https://docs.google.com/spreadsheets/d/1blKG8VrvGIqGfGxz9y_Jh-mlnNYOT0aMiYZb1axfzM4/edit#gid=1760670330

- [x] One question to be added for PMSMA. Details in Ref document
- [x] Do not allow adding more than 5 ANCs (regular case) and 7 ANCs (HRP case). Logic in Ref document for ANC field
- [x] Additional option to be added in Bank Account / Post Office Question
- [x] Future date should not be allowed in Marriage date
- [x]  If it's not her 1st pregnancy then Gravida should not be less than 2 and parity should not be 0.
- [x]  Marriage date should not show if age <15
- [x]  Sterilisation option should not show if age < 15
- [x]  Change the Household Name label to Household Number
- [x]  House Ownership answers to be as per ref document should show Rented / Owned.
- [x]  Household Amenities is written as "Householod amenities"
- [x] Individual Registration First Name and Last Name should show allow only alphabets
- [x] "Confirm Pregnancy by issuing Nischay Kit" should show when the Pregnancy Test done answer is No
- [x] Spelling mistake in the message  : Nikshay  -> Nischay
- [x] Approximate last dose date should now allow future date
- [x] Refer to vhsnd date must not allow date less than enrolment date time.
- [x] Should not be more than 5 weeks old from Enrolment date and not greater than today's date with a message saying "LMP date cannot be more than 5 weeks in the past or in the future".
- [x] When "Is any ANC done" answer is "Yes", then "0" answer must not be shown in "How many ANC done".
- [x] Place of reference must not appear if "Whether beneficiary referred for consultation" answer is "No" AND "Whether beneficiary referred for HRP confirmation" answer is "No".

**Comment by AchalaBelokar** [comment]
The marriage date should not show if age <15
 Sterilization option should not show if age < 15
not appearing  for age 15

Fathers name and Mothers name should allow only alphabets
