### ISSUE TITLE
Avni AMRIT Mapping Analysis

### ISSUE THREAD

**Issue by arjunk** [avniproject/SAKHI#20]
Reference folder / documents
https://drive.google.com/drive/folders/1qWX8XvQRt-cD5KbmPjqlNzzsBoBUSlL0

https://docs.google.com/spreadsheets/d/10bLYLJlqn8AXTamAncE-iscytiQZbRA9L2lnZNjqUd8/edit#gid=0

Registration Form
- [x] Amrit mandatory fields with Avni fields and mandatory status
- [x] Amrit conditional mandatory fields with Avni fields and conditional status
- [x] Amrit master fields with Avni fields and answers

CBAC
- [ ] Amrit mandatory fields with Avni fields and mandatory status
- [ ] Amrit conditional mandatory fields with Avni fields and conditional status
- [ ] Amrit master fields with Avni fields and answers

**Comment by utkarshavni** [comment]
Have updated mapping for Registration - those not clear or not available in Avni highlighted in Yellow. Household and CBAC details are awaited.
