### ISSUE TITLE
Dawa Prapatra

### ISSUE THREAD

**Issue by sachsk** [avniproject/SAKHI#21]
![image.png](https://images.zenhubusercontent.com/5dc4129311dec50001487a46/0b039087-a179-4c84-a473-319cf3579377)

**Comment by nupoorkhandelwal** [comment]
Moved this to production Sakhi App.

**Comment by AchalaBelokar** [comment]
the count of 4 visits anc completed but in dawa   prapatra value is not reflecting

**Comment by AchalaBelokar** [comment]
the count of 4 visits anc completed but in dawa   prapatra value is not reflecting

**Comment by AchalaBelokar** [comment]
- [x] Also offline dashboard is not working

**Comment by AchalaBelokar** [comment]
In different  login it is showing same values.
I login with AchalaB@sakhiapp

![Screenshot 2022-10-14 at 4.28.16 PM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/1546cf7b-61f4-4fe0-9968-7041bcdab01e)


When I login with Ach@sakhiapp



![Screenshot 2022-10-14 at 4.30.23 PM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/4e393ffe-4d46-43e1-8863-82923db47c85)

**Comment by AchalaBelokar** [comment]
In different  login it is showing same values.
I login with AchalaB@sakhiapp

![Screenshot 2022-10-14 at 4.28.16 PM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/1546cf7b-61f4-4fe0-9968-7041bcdab01e)


When I login with Ach@sakhiapp



![Screenshot 2022-10-14 at 4.30.23 PM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/4e393ffe-4d46-43e1-8863-82923db47c85)

**Comment by AchalaBelokar** [comment]
In Dawa Prapatra every user is showing the same Uuid.
