### ISSUE TITLE
[SAKHI 2.0] HBNC Form

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/SAKHI#23]
https://docs.google.com/spreadsheets/d/1cnKVDu6VIGpYzVkNh8PF-6wDoM-dXSmv/edit#gid=1996173979

- [x] Create a program encounter HBNC, under Child program.

- [x] Add encounter eligibility check to hide this visit from unplanned visits as this will be planned visit.

- [x] Schedule the first HBNC during child enrolment as per the following schedule-
[1 ,3,7,14,21,28,42]

Logic for visit scheduling-
For "Place of Delivery" in child form = Home then start scheduling from 1st day of delivery.
For "Place of Delivery" in child form != Home then start scheduling from 3rd day of delivery.
For "Type of delivery" in child form = C-Section then start scheduling from 7th day of delivery.

- [x] Cancel form should schedule the respective visit as per above schedule.

**Comment by Gojo-Taqi** [comment]
For "Place of Delivery" in child form = Home then start scheduling from 1st day of delivery.
For "Place of Delivery" in child form != Home then start scheduling from 3rd day of delivery.
For "Type of delivery" in child form = C-Section then start scheduling from 7th day of delivery.

Is remaining

**Comment by AchalaBelokar** [comment]
When I edit the birth date of the child after that hbnc form is not reflecting the data.

**Comment by AchalaBelokar** [comment]
- [ ] At what time was the baby first breastfed? this question should be auto-populated.

**Comment by AchalaBelokar** [comment]
- [x] Green These fields will be asked only in the first HBNC.

**Comment by Gojo-Taqi** [comment]
@AchalaBelokar You should not take those colour code seriously, Nupoor had told to follow the validation written in the validation column.
And not to worry about the colour.
Moving it back to QA ready
