### ISSUE TITLE
[SAKHI 2.0] Abortion form

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/SAKHI#24]
https://docs.google.com/spreadsheets/d/18y7ifdXUsdUp7l4VgGXEEU1eApdJoGBw/edit#gid=364953652

- [x] Create a program encounter Abortion, under Pregnancy program.
It will be an unplanned encounter so no need for visit scheduling.

- [x] Add encounter eligibility check to hide this visit from unplanned visits, if Delivery or Abortion is filled in this program.

**Comment by Gojo-Taqi** [comment]
Since there is no delivery form created yet, added the rule for abortion only
