### ISSUE TITLE
[SAKHI 2.0] Delivery Form

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/SAKHI#25]
https://docs.google.com/spreadsheets/d/1cnKVDu6VIGpYzVkNh8PF-6wDoM-dXSmv/edit#gid=1474207435

- [x] Create a program encounter Delivery, under Pregnancy program.
It will be an unplanned encounter so no need for visit scheduling.  
**Updated - from UAT Feedback the Delivery encounter is required to be scheduled on Expected date of delivery**

- [x] Add encounter eligibility check to hide this visit from unplanned visits, if Delivery or Abortion is filled in this program.

**Comment by utkarshavni** [comment]
1.    Added date validations in couple of fields and validation for RCH id.
2.   Do we need to add normal range for infant’s temperature, weight fields?
3.   Do we need to add format validation for child identification number and birth certificate number?

**Comment by utkarshavni** [comment]
- [ ] The form is scheduled based on LMP. It is supposed to be an unplanned visit.
- [x] Outcome of delivery field is not shown when Mother's condition is Death.

**Comment by Gojo-Taqi** [comment]
Outcome of delivery will show only on entering both the values in the form
About scheduling, I'll confirm with the BA once and fix if required

**Comment by Gojo-Taqi** [comment]
This form will be scheduled on EDD.
Confirmed with the BA on this

**Comment by utkarshavni** [comment]
@Gojo-Taqi 

- [x] Add a check on auto populated count of total children that it cannot be less than 1. Currently we are allowing user to enter 0 in both live birth and still birth and in that case the  delivery outcome is not displayed. So it should be displayed and throw the error that delivery outcome can not be less than 1.

**Comment by AchalaBelokar** [comment]
https://app.zenhub.com/workspaces/product-635b73bded85e50018871ae6/issues/avniproject/avni-client/750 blocked
