### ISSUE TITLE
[SAKHI 2.0] PNC Form

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/SAKHI#26]
https://docs.google.com/spreadsheets/d/1cnKVDu6VIGpYzVkNh8PF-6wDoM-dXSmv/edit#gid=1019844557
(For now, don't include the Child PNC details, highlighted in green color)

- [x] Create a program encounter PNC, under Pregnancy program.

- [x] Add encounter eligibility check to hide this visit from unplanned visits as this will be planned visit.

- [x] Schedule the first PNC during delivery as per the following schedule-
[1 ,3,7,14,21,28,42]

Logic for visit scheduling-
For "Place of Delivery" in Delivery form = Home then start scheduling from 1st day of delivery.
For "Place of Delivery" in Delivery form != Home then start scheduling from 3rd day of delivery.
For "Type of delivery" in Delivery form = C-Section then start scheduling from 7th day of delivery.

- [x] Cancel form should schedule the respective visit as per above schedule.

- [x] No PNC should get scheduled, in case "Mother's Condition" = "Death" in delivery form.

**Comment by utkarshavni** [comment]
- [x] PNC Period is not auto-populated (based on difference between today's date and delivery date
- [ ] Completing PNC visit with selecting No in Family planning being used and then while editing the visit, user is not able to select Yes. Clicking on Yes does not do anything.
- [x] Editing PNC should not schedule next PNC if next PNC is already scheduled.
- [x] Spelling of Haemorrhage is incorrect. 
- [x] Fill a delivery form with Type of delivery not as C-section, go to last page and do not click on Save. The summary page displays PNC 1 under Visits being scheduled. Now go previous, change type of delivery as C section, and navigate to last page. The visits being scheduled section shows two visits - It should only show one visit based on C-section rule and not the previously scheduled visit.
Screenshot:![Visit scheduling summary issue.jpg](https://images.zenhubusercontent.com/61dbee9a6fc777578773b609/8110e14c-d126-4456-9674-e92bc488e567)

**Comment by Gojo-Taqi** [comment]
Anaemia is the right spelling

**Comment by Gojo-Taqi** [comment]
PNC period is not required
