### ISSUE TITLE
[SAKHI 2.0] HBYC form

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/SAKHI#27]
https://docs.google.com/spreadsheets/d/1cnKVDu6VIGpYzVkNh8PF-6wDoM-dXSmv/edit#gid=1974533929

- [x] Create a program encounter HBYC, under Child program.

- [x] Add encounter eligibility check to hide this visit from unplanned visits as this will be planned visit.

- [x] Schedule the first HBYC during HBNC/child enrolment as per the following schedule-
HBYC 1 - 3 month from date of birth
HBYC 2 - 6 month from date of birth
HBYC 3 - 9 month from date of birth
HBYC 4 -12 month from date of birth
HBYC 5 -15 month from date of birth

- [x] Cancel form should schedule the respective visit as per above schedule.

**Comment by AchalaBelokar** [comment]
- [x] ORS at home?   this question should show HBYC 2,3,4,5 currently it is showing in the HBYC 1 also

- [x] IFA syrup at home? this question should show HBYC 2,3,4,5 currently it is showing in the HBYC 1 also

- [x] 	Measles vaccine given? this question is missing in the form HBYC 4, HBYC 5, HBYC 3
- [x] 	Vitamin A given?his question is missing in the form HBYC 4, HBYC 5, HBYC 3

**Comment by AchalaBelokar** [comment]
- [ ] for 3 moths it is scheduling the HBYC 2

**Comment by AchalaBelokar** [comment]
- [ ] Schedule the first HBYC during HBNC/child enrolment as per the following schedule-
HBYC 1 - 3 month from date of birth.

- [x] IFA syrup given? showing for 3 month

- [x] Counsel for exclusive breastfeeding?If "HBNC Visit" =  3 month, 6 month
showing HBYC needs to check HBYC 3,4,5
