### ISSUE TITLE
[SAKHI 2.0] Family Planning Program and forms

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/SAKHI#29]
https://docs.google.com/spreadsheets/d/1cnKVDu6VIGpYzVkNh8PF-6wDoM-dXSmv/edit#gid=2109116067

- [x] Create a program - Family planning
https://docs.google.com/spreadsheets/d/1cnKVDu6VIGpYzVkNh8PF-6wDoM-dXSmv/edit#gid=2109116067

- [x] Create program encounter - FP Followup
https://docs.google.com/spreadsheets/d/1cnKVDu6VIGpYzVkNh8PF-6wDoM-dXSmv/edit#gid=1904707969

**Comment by Gojo-Taqi** [comment]
Add program eligibility check :-
- [x] Is female and Age greater than 18
- [x] If male, age greater than 21

**Comment by AchalaBelokar** [comment]
- [x] Family planning Enrolment 1st date of the child needs validation.

- [x] 2nd child date of birth needs a validation.

**Comment by AchalaBelokar** [comment]
- [x] Family planning Enrolment 1st date of the child needs validation.

- [x] 2nd child date of birth needs a validation.

**Comment by AchalaBelokar** [comment]
- [x] Is female and Age greater than 18 

- [x] If male, age greater than 21
