### ISSUE TITLE
[SAKHI] User is able to register a beneficiary in the system

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/SAKHI#3]
**Motivation:**
The ASHA will register individual beneficiaries during door to door survey of households. Details of different family members are required to be added in the system.

**Goal:**
User is able to register Individual in the application with fields as mentioned in the form with required validations and skip logic.
Form link: 
https://docs.google.com/spreadsheets/d/1blKG8VrvGIqGfGxz9y_Jh-mlnNYOT0aMiYZb1axfzM4/edit#gid=70907390

**Acceptance criteria:**
User should be able to register Individual in the application when all the mandatory fields have been answered.
The skip logic for the questions should be working correctly as mentioned in the form.
The validations for different questions should be triggered as mentioned in form.

**Comment by AchalaBelokar** [comment]
1)Educational Qualification when to show: Only if age is above 14
2) Occupation when to show: Only if age is above 14
