### ISSUE TITLE
SAKHI UAT Feedback

### ISSUE THREAD

**Issue by arjunk** [avniproject/SAKHI#30]
Reference :
https://docs.google.com/spreadsheets/d/1gzBheHfP6rQzbAnQMuz4wJr33Mo2T4EzPmvR_RT3Ba4/edit#gid=0

- [x] Validation to be added to not allow ANC date to be within (less than) 30 days of the previous ANC visit. Message "Two ANC visits should be 30 days or more apart"

- [ ] Bug 
Home Screen>> click on search >> select individual >>
 Type "Raja" in Name field>>  click on submit >> select Raja Ram (5years) >> Click on profile >> Click on Add relative >> Search "singh" as a Household >> Click on Submit >> Select Vinod Singh >> Fatal error appears 

- [ ] Bug
 Go to Eligible Female >>tap on any beneficiary with household (e.g. Seeta Ram)>>  tap on her household (i.e. Rampura Household >> edit details of household >> Change Household number/name to "Rampura Seeta" >> Next>> next >> Observe >> Blank white screen is getting shown

- [x] Add a validation check such that the marriage should not be less than DoB + 15 years. Message: "Age at the time of marriage can be less than 15"

- [x] Name fields should allow apostrophe e.g. Thomash D'Souza

- [x] Individual Registration : In case of marital status selected as Divorce then spouse name should be disabled

- [x]  Under Child Death Review,Add validation on "Date and time of death" field not to accept future date and time

- [x] In Household numbers, only numerical values should be allowed

- [x] Block and district should be available for Household registration 

- [x] Does your family have an AB PMJAY card?
AB PMJAY card No. - Add these fields in HH registration.

- [x] Add "Age at the time of marriage"  in individual registration

- [x] ANC- Add valid range on HB and Weight fields

- [x] Replace  "Date of Sterilization"  as "Date of Birth control method" in Family Planning  

- [x] Pregnancy enrolment - After selecting Yes option for Are you taking any medicine?
 The "Please select the disease" option is not coming

- [x] Update ANC visit scheduling to show number of visit in the visit name

- [x] Pregnancy enrolment - Do you want to continue with the pregnancy?. Update visit scheduling as per the answer.

- [x] Correction in the MCP logic :- If beneficiary has the MCP card then data fields like date  of registration, place of registration, ANC done or not etc should be visible 

Points to be analysed
- TD dose Logic Correction : 
1. If total count of last dose is 0 and 1 then it should display the tentative date of TD1 only.
2. 1. If total count of last dose is 2  then  its is asking only approximate date of last dose 
which is fine but apart from this it should also display whether the beneficiary will get
 TD1 or TD booster as per the logic in Google sheet given by us.
- The TD logic must be carried forward in the ANC.Please refer the Google excel sheet for logics

**Comment by utkarshavni** [comment]
- [x] When date of birth is 25 December, 1992 and Date of marriage  was kept to any date between 1st december and 25th december, it was allowing. It seems to be considering the month and year only for validation.
- [x] When do you want to continue with pregnancy is selected as No, it is scheduling Delivery form, it should schedule Abortion form.
- [x] In Child death review, when time selected is of future, the validation message is incorrect.


Attaching screenshots: 
![Incorrect validation message.jpg](https://images.zenhubusercontent.com/61dbee9a6fc777578773b609/cd5a9172-f293-4bdb-acc4-767f9280f075)
![Validation message should be correct for time.jpg](https://images.zenhubusercontent.com/61dbee9a6fc777578773b609/560d3f50-655f-4b5c-8e58-d1f1bd69b518)![Abortion not scheduled.jpg](https://images.zenhubusercontent.com/61dbee9a6fc777578773b609/e47ffed7-5662-43f9-9496-7defef74362d)

**Comment by utkarshavni** [comment]
For the first bug item mentioned in the requirement - card has been created for platform:
https://github.com/avniproject/avni-product/issues/1283

The second one is only happening for that specific individual.

**Comment by AchalaBelokar** [comment]
- [ ] needs to clear the last thing TD dose logic

**Comment by AchalaBelokar** [comment]
- [ ] Pregnancy enrolment - Do you want to continue with the pregnancy?. Update visit scheduling as per the answer. this question is not available in the Pregnancy enrolment form
