### ISSUE TITLE
[SAKHI] Edit visit scenarios are not handled

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/SAKHI#31]
**Issue**
On editing a form, it should not schedule subsequent visit if it is already there. i.e. On editing Pregnancy enrolment, if ANC 1 is already there, it should not schedule the visit.

**Goal**
For all the encounters wherever visit is scheduled on submit, put check that it should schedule subsequent visit only if it is not there already.

**Screenshot:**
![Edit visit scenarios.jpg](https://images.zenhubusercontent.com/61dbee9a6fc777578773b609/199da644-cd88-47cc-8dcf-bd0390043f2e)

**Comment by Gojo-Taqi** [comment]
Edit scenarios have been handled for ANC, PNC, HBNC, HBYC
