### ISSUE TITLE
[SAKHI] Phase 1 & 2 - UAT Feedback

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/SAKHI#34]
**All Forms:** 
- [x] Whenever a form is saved and observation summary is displayed on last page, it should show all the fields entered - right now it does not show all observations. (forms for example: Household Registration, PW Enrollment, Abortion)

**Dashboard**
- [ ] Due visits card is displaying Overdue visits - beneficiary "Fm fm"
- [x] Cards to be created for CBAC with titles:
a) Completed - to show list of individuals with CBAC filled
b) Not Completed - to show list of individuals with CBAC not filled
- [x] Remove "Eligible couple - Male" card

**Search Filters**
- [ ] When Household is selected in Search page for the subject, the "Name" field displayed should display "Number" since the user is entering Household number in form.
- [x] Add filters of Mobile No, RCH ID, ABHA ID for Individual.

**Individual Registration:**
- [x] In Marital Status options, hide "Widow" if gender is "Male" or Hide "Widower" if gender is "Female"

**Household Registration**
- [x] Add a field for Household Name. This is so that when ASHA searches for a Household by Household number, the list items should display the name as well. (i.e. If an ASHA searches by "11" and the list shows 11,1011,111 in the list - having the name of household in the list will help ASHA in selecting a correct household.
- [x] Add validation for AB PMJAY card number - it should be Alphanumeric, only allow 10 characters and all letters to be in capital.
- [x] Total members field is not displayed while editing the registration and also when one clicks on the down arrow from profile page to expand the form and see fields.
- [x] While adding a member, it shows "Head of Family" option in relationships even when Head of household is already available. 

**Pregnancy Enrollment form:**
- [x] Next ANC date in Antenatal services section should auto populate the date of 28 days after the date given for Last ANC date.
- [x] LMP date should not allow user to select a date that is older than 5 weeks from Enrollment  date.
- [x] When Doses taken in previous pregnancy is 0 or 1, it should display Tentative date for TD1 only. This is because Dose 1 date is updated in ANC - once there is actual date available for TD1 only then it makes sense to show date for TD2.
- [x] When Doses taken in previous pregnancy is 2 and Approximate date is less than 30 months from current date, it should display Tentative TD booster dose date field only.
- [x] When Doses taken in previous pregnancy is 2 and Approximate date is more than 30 months from current date, it should display Tentative TD dose 1 date field only.

**ANC Form**
- [x] Difference of dates between two ANCs should be 28 days or more, it should not allow to select a date that is within 28 days of previous ANC.
- [x] When ANC1 and ANC 2 has been done, and we are again editing ANC1 the  ANC 2 is converting into ANC 3

**Abortion Form**
- [ ] Only to be shown for a beneficiary in their 1st and 2nd trimester

**Family Planning:**
- [x] Date of marriage should auto populate from individual's registration details.

- [x] All Mother and Child Program encounters should provide the option to Cancel the visit and when visit is cancelled, the cancellation form reasons should be same as provided in PNC.

**Comment by Gojo-Taqi** [comment]
Points to confirm with the BA :- 
- [ ] TD1 and TD2 dose dates are displayed same.

For the point "When Household is selected in Search page for the subject, the "Name" field displayed should display "Number" since the user is entering Household number in form.", it does search with household number, it's just that it says name.

**Comment by utkarshavni** [comment]
Due visits displaying Overdue visits - this is happening for a border line case, a card for product has been created. 
https://app.zenhub.com/workspaces/avni-product-635b73bded85e50018871ae6/issues/gh/avniproject/avni-client/758

**Comment by AchalaBelokar** [comment]
- [ ] Whenever a form is saved and observation summary is displayed on last page, it should show all the fields entered - right now it does not show all observations. (forms for example: Household Registration, PW Enrollment, Abortion)
not to be tested

**Comment by AchalaBelokar** [comment]
- [ ] Whenever a form is saved and observation summary is displayed on last page, it should show all the fields entered - right now it does not show all observations. (forms for example: Household Registration, PW Enrollment, Abortion)
not to be tested

**Comment by AchalaBelokar** [comment]
- [x]  Difference of dates between two ANCs should be 28 days or more, it should not allow to select a date that is within 28 days of previous ANC.
logic
