### ISSUE TITLE
[SAKHI] Changes in HBNC Visit

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/SAKHI#36]
There are questions which are only required to be asked in first HBNC visit as those details are not collected every time when ASHA visits the mother.

The fields only to be shown for 1st HBNC visit are highlighted in green in the requirement sheet updated:
https://docs.google.com/spreadsheets/d/1cnKVDu6VIGpYzVkNh8PF-6wDoM-dXSmv/edit#gid=1996173979

**Comment by AchalaBelokar** [comment]
- [x] Temperature (in °F) of the baby 96-99.6. 
I fill the the normal range still Action taken question  is appearing. condition is given below."If ""Temperature (in °F) of the baby"" >  99.5 °F OR less than 95.9 °F and only for 1st HBNC"

- [x] Has umbilical cleaned by ANM /ASHA  skip logic is missing  for this question.


- [x] Part 2 - Infant first physical observation . Appearing  second visit also.
