### ISSUE TITLE
[SAKHI] Dawa Prapatra Phase 2

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/SAKHI#38]
## Context
Dawa Prapatra is a document that ASHA has to submit to claim incentives for the work that she has done in the month. There are activity code related to each activity and associated rate. She has to provide the following key information
- Activity Code
- Rate
- Beneficiary Count
- Total claim amount
- Start Date
- Completion date

In Phase 2, following forms activity details will be generated in Dawa Prapatra.
- [x] Abortion
- [x] Delivery
- [x] PNC (This is included as part of HBNC and HBYC only, so there is no separate activity code for this in the sheet).
- [x] HBNC and HBYC

Requirement sheet:
https://docs.google.com/spreadsheets/d/14vjke5eR8-afiRXKUQalxDk0E12ktltVLt1Zq_rq3AI/edit#gid=0

**Comment by AchalaBelokar** [comment]
Two user is showing the same data

**Comment by AchalaBelokar** [comment]
- [ ] I enter the data AchalaB@sakhiapp after 2 hr it is not reflecting in the app

**Comment by AchalaBelokar** [comment]
- [ ] there are chandu individual in AchalaB@sakhiapp. which is not reflected in the app.

**Comment by AchalaBelokar** [comment]
- [x] HBNC is not reflecting
