### ISSUE TITLE
[SAKHI] Changes in due and overdue logic for vaccination

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/SAKHI#40]
- [x] Change Due, Overdue and Expired logic based on the values shown in "Due/Overdue/Expired" Column in the requirement sheet: Remove logic for vaccines to be displayed under critical.
https://docs.google.com/spreadsheets/d/1cnKVDu6VIGpYzVkNh8PF-6wDoM-dXSmv/edit#gid=140620644
- [x] Check when to show logic as well as "Due/Overdue/Expired" logic for all Vitamin A doses.

**Comment by AchalaBelokar** [comment]
- [ ] After 45 days BCG showing in due .it should be overdue.

- [ ] expire date logic are missing

**Comment by AchalaBelokar** [comment]
Pls refer the individual  Tota Tota 
the vitamin  A1 is showing in 3.5 year old girl which is not in the requirement.
I should be shown  after 9 month
