### ISSUE TITLE
[Sakhi] User is able to enrol benificary in Malaria program and exit from it.

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/SAKHI#41]
- Create a Program called Malaria.
- Enrollment form - Malaria enrollment form
- Exit form - Malaria exit form

Form requirements:
https://docs.google.com/spreadsheets/d/1HMAVYsJzpr23R_fxFmMfoEBpruCHEa1J/edit#gid=140620644

**Comment by Gojo-Taqi** [comment]
time taken to complete :- 15 mins
