### ISSUE TITLE
[Sakhi] User is able to enroll in and exit individual from program Filaria

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/SAKHI#46]
- [x] Create a program called Filaria
- [x] Program enrollment form: Filaria enrollment form
- [x] Program exit form: Filaria exit form

Form requirements:
https://docs.google.com/spreadsheets/d/1HMAVYsJzpr23R_fxFmMfoEBpruCHEa1J/edit#gid=222457905

**Comment by Gojo-Taqi** [comment]
Time taken to completed :- 20 mins

**Comment by AchalaBelokar** [comment]
- [ ] Display "P" If beneficary is enrolled in pregnancy program, Display "Y" If "Age" less than 2 year and should be non-editable
 it is editable

**Comment by Gojo-Taqi** [comment]
We cannot make any question editable or non editable on a condition, hence pushing this card back to QA ready
