### ISSUE TITLE
[Sakhi] User is able to complete follow-up for Malaria patient

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/SAKHI#49]
- [x] Create a program encounter called "Malaria follow-up"
- [x] The encounter will be unplanned
- [x] Form requirements:
https://docs.google.com/spreadsheets/d/1HMAVYsJzpr23R_fxFmMfoEBpruCHEa1J/edit#gid=672909643
- [x] Encounter should not be visible once Malaria case status is "Treatment completed" OR when patient has exited from program.

**Comment by AchalaBelokar** [comment]
- [ ] I selected treatment completed still it is visible
