### ISSUE TITLE
[SAKHI] User is able to enrol a woman into Pregnancy program

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/SAKHI#5]
**Motivation:**
Once a woman is pregnant, ASHA is required to do regular follow-up, maintain record and make sure that the woman gets the access to health care required and benefits of other schemes she is eligible for. The Pregnancy related details till delivery is part of the Pregnancy module.

**Goal:**
User is able to enroll a woman in pregnancy program when 
- [x] Her age is between 18 to 49 years.
- [x] Is Sterilization done in Registration has answer No.
- [x] Gender is Female

The Program enrollment should not be eligible unless this criteria are met.
Form link:
https://docs.google.com/spreadsheets/d/1blKG8VrvGIqGfGxz9y_Jh-mlnNYOT0aMiYZb1axfzM4/edit#gid=404429529

**Acceptance Criteria**
User is able to enroll a pregnant woman into program with all the required fields with the validations, skip logic and all the mandatory fields.

**Comment by AchalaBelokar** [comment]
1) The estimated Date of Delivery should be auto calculated 
<img width="376" alt="Screenshot 2022-07-27 at 4 32 58 PM" src="https://user-images.githubusercontent.com/104890488/181232128-bdd6b7ab-141f-45b7-b7c0-80cbd5496d28.png">

If the answer of Suspected High-Risk Pregnancy is yes then it will show in red colored.

**Comment by Gojo-Taqi** [comment]
Fixed the first issue.
For the second issue, it's a bug and that cannot be highlighted in red when there is only one option shown.

**Comment by Gojo-Taqi** [comment]
Added a extra field **"Tentative TD 2 Date (VHND / PMSMA)"**.
Removed the auto populate logic for **"Tentative TD 1 Date (VHND / PMSMA)"** and **"Tentative Date for Booster (VHND / PMSMA)"**.
Added **Height**.

**Comment by AchalaBelokar** [comment]
Remove Actual Delivery Place  fro the form
