### ISSUE TITLE
[Sakhi] User is able to enroll in and exit individual from Leprosy program

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/SAKHI#51]
- [x] Create a program Leprosy
- [x] Program enrollment form - "Leprosy enrollment form"
- [x] Program exit form - "Leprosy exit form"

Form requirements:
https://docs.google.com/spreadsheets/d/1HMAVYsJzpr23R_fxFmMfoEBpruCHEa1J/edit#gid=2116576985

**Comment by AchalaBelokar** [comment]
skiping logics are missing

**Comment by utkarshavni** [comment]
@AchalaBelokar @Gojo-Taqi  Skip logic for Type of Leprosy was missing which is added. Rest is working fine. Moving to QA Ready.
