### ISSUE TITLE
[Sakhi] User is able to complete TB follow-up for individual.

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/SAKHI#54]
- [x] Create a program encounter called "Tuberculosis follow-up"
- [x] Encounter is unplanned
- [x] Encounter will be not shown if status is expired/patient has died.

Form requirements:
https://docs.google.com/spreadsheets/d/1HMAVYsJzpr23R_fxFmMfoEBpruCHEa1J/edit#gid=1888746608

**Comment by AchalaBelokar** [comment]
- [x] If "TB Case" = "Suspected" skip logic is missing 

- [x] Type of TB  If "TB Case" = "Confirmed"

- [x] Treatment Start Date If "TB Case" = "Treatment Started"

**Comment by AchalaBelokar** [comment]
- [x] same with follow up
