### ISSUE TITLE
[Sakhi] CBAC form updates

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/SAKHI#55]
CBAC form needs to be updated based on changes provided in third phase.

Form requirements:
https://docs.google.com/spreadsheets/d/1HMAVYsJzpr23R_fxFmMfoEBpruCHEa1J/edit#gid=1436598693

- Fields in green legend are already there.
- Fields with yellow legend are already there but needs to be updated based on logic provided.
- Keep the sequence of questions and page as displayed in the sheet.

**Comment by AchalaBelokar** [comment]
- [x] skip logic is missing.
If option selected is "Yes" then display "Collect the cough sample and take it to the nearest TB Test center for testing purpose."

- [x] Ulcers in Mouth Not Healed in 2 weeks
Growth in Mouth Not Healed in 2 weeks
Any white or red Patch in Mouth Not Healed in 2 weeks these are diffrent question

- [x] auto population logic is working wrongly 
[https://app.zenhub.com/files/503244001/011b3f0a-aee3-423f-a680-51f492291069/download](https://app.zenhub.com/files/503244001/011b3f0a-aee3-423f-a680-51f492291069/download)

**Comment by AchalaBelokar** [comment]
- [x] Difficulty in reading question is missing .

- [x]  TB related question skip logic is missing.

**Comment by AchalaBelokar** [comment]
![Screenshot 2023-02-16 at 6.36.26 PM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/8ac61a66-c59c-42e8-8ce3-35d67153f3a2)

If selected Yes in any of the questions from 1 to 6 show this answer. I selected NO all answer still  it is showing me note
Collect the cough sample and take it to the nearest TB Test center for testing purpose

**Comment by AchalaBelokar** [comment]
![Screenshot 2023-02-16 at 6.36.26 PM.png](https://images.zenhubusercontent.com/62722c06dedab50580ce62fa/8ac61a66-c59c-42e8-8ce3-35d67153f3a2)

If selected Yes in any of the questions from 1 to 6 show this answer. I selected NO all answer still  it is showing me note
Collect the cough sample and take it to the nearest TB Test center for testing purpose

**Comment by Gojo-Taqi** [comment]
Achala In your screen shot, we can clearly see the first questions answer is yes. 
Which is one of the six questions we are talking about.
