### ISSUE TITLE
[Sakhi] Pending Dawa Prapatra items

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/SAKHI#56]
**Reference sheet**
https://docs.google.com/spreadsheets/d/14vjke5eR8-afiRXKUQalxDk0E12ktltVLt1Zq_rq3AI/edit#gid=0

Activities for which Dawa prapatra needs to be populated with details:

- [x] I1.1 - ANC done under PMSMA  
- [x] I2.1 and I2.2 - Permanent family planning method adopted by individual
- [x] I2.3 - Post delivery permanent family planning method adopted by mother
- [x] I2.4 - Family planning method adopted post abortion
- [x] I2.5 - Post delivery temporary family planning method adopted by mother [Copper T]
- [x] I2.7 - Individual for whom difference of two children's date of birth is more than 3 years
- [x] I2.8 - Couple encouraged to adopt permanent family planning method after having second child
- [x] I8.1 - Patient confirmed for TB
- [x] I8.13 - Individual enrolled in AES JE program and referred to a govt health facility
- [x] C3.4 - Routine immunization for a child within a year from birth
- [x] C3.5 - Routine immunization for a child within two years from birth
- [x] C3.6 - DPT Booster 2 given to a child
- [x] C7.1 - CBAC form is filled for the individual 
- [x] Activity codes C1.8 and C1.9 had incorrect logic - the correct logic has been updated in sheet: re-write the logic.
https://docs.google.com/spreadsheets/d/14vjke5eR8-afiRXKUQalxDk0E12ktltVLt1Zq_rq3AI/edit#gid=0

**Comment by Gojo-Taqi** [comment]
Estimated time of completion :- 1.25 day

**Comment by AchalaBelokar** [comment]
- [x] I8.1 - Patient confirmed for TB

- [x] I2.4

- [x] C4.1 

- [ ]  I1.1 - ANC done under PMSMA individual name AB

- [ ] C3.4 Routine immunization for a child within a year from birth Individual  name Baby one

- [ ]

**Comment by AchalaBelokar** [comment]
- [x] HBNC is not working

- [x] I8.1 is not working
