### ISSUE TITLE
[SAKHI] UAT Misc issues

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/SAKHI#57]
**PNC:**
- [x] If Mother's condition post delivery is marked as "Death", the next PNC should not be scheduled.
- [x] On editing PNC 1, PNC 2 is converted to PNC 3.
- [x] Update Child PNC details in the PNC encounter of mother, as refered in the sheet. The questions should show twice if the delivery outcome says 2. Show the questions based on the number of children given birth during delivery.
https://docs.google.com/spreadsheets/d/1cnKVDu6VIGpYzVkNh8PF-6wDoM-dXSmv/edit#gid=1019844557

**TB Follow-up**
- [x] If Status is "Cured" or "Expired" or Patient status is "Recovered" then do not show the TB follow-up form in unplanned visit.

**Comment by AchalaBelokar** [comment]
- [ ] TB Recovered feild is missing according to that we need to schedule  follow up
