### ISSUE TITLE
 [Sakhi] Feedback items to go live

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/SAKHI#58]
- [x] For any of the programs, if the individual has expired (death), then option to enroll in any program should not be shown.
- [x] TD dates are not displayed in the Pregnancy enrollment.
- [x] Individual till 14 years of age should be eligible for enrollment in Child program.
- [x] Add following Activity codes in Dawa Prapatra
I8.14, I8.15, I8.17
Requirements:
https://docs.google.com/spreadsheets/d/14vjke5eR8-afiRXKUQalxDk0E12ktltVLt1Zq_rq3AI/edit#gid=0

**Comment by Dinesh2019** [comment]
when we enrol the individual in any program and exit the individual as death the enroll option should not displayed.But when we undo the exit enrolled the enroll option for the program should be displayed.
Step to reproduce:
1.Login to sakhiapp
2.Create the indiviudal
3.Enroll in the program.
4.Exit the enroll as death.
5.Again undo the exit enroll.
Excepeted result : Enroll option should be displayed.
Actual result : option is not displayed:
Screenshot with enroll option before exit:
![image.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/c2d4e726-9532-461f-ae2c-fd46115c043b)
Screenshot after exit as death:
![image.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/8d0efc81-b561-45f7-9e29-f14a3948cf5a)
After undo the exit enroll:
![image.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/6e826aff-0dcb-4b67-b8a2-8b18c12ed8da)

Waiting for the confimation for Taqi so we are having it as QA Ready
