### ISSUE TITLE
[SAKHI] ANC Visits

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/SAKHI#6]
**Motivation**
Once a woman is registered and ASHA is aware about the pregnancy, she will help facilitate periodic visits for basic check-ups and make sure any precautions if required are taken and treatment is provided to beneficiary whenever needed.

https://docs.google.com/spreadsheets/d/1blKG8VrvGIqGfGxz9y_Jh-mlnNYOT0aMiYZb1axfzM4/edit#gid=1760670330

**Goal:**
1. ASHA should be able to fill the ANC form with fields as described in the link above
2. All the skip logic,  validation and other rules should work as described in the link above

**Comment by AchalaBelokar** [comment]
when we click on Place of ANC we choose Other it will show the other ANC place

**Comment by AchalaBelokar** [comment]
If the result of the pregnancy  is negative then no ANC visit  should be scheduled
