### ISSUE TITLE
[SAKHI] Bug Fixes

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/SAKHI#60]
- [x] Auto populate Date of marriage in Family planning enrollment if available and selected in Individual registration.
- [x] Date of Marriage field in Registration and enrollment should not allow future date.
- [x] "180 Iron Folic Acid tablet issued or not" question is not visible while doing an ANC but only visible while editing it.
- [x] Rename "Household number" as "House number" through translation.
- [x] If the "Result of Pregnancy test" is negative in pregnancy enrolment then hide following fields:
1. Previous pregnancy details section
2. Antenatal services section
3. Vaccination section
4. High Risk pregnancy section
5. Next ANC date section
- [x] More than 5 ANCs should not be scheduled for a pregnant woman unless she is high risk pregnancy.
- [x] Disable Pregnancy enrolment if the Individual registration form has answer "Yes" for adopted any permanent birth planing method.
- [x] Keep validation for Post office account no to be not greater than 12 digits.
- [x] Keep validation for Bank account no to not be greater than 14 digits.
- [x] For Bank name concept, do not allow numeric values.
- [x] In ANC encounter, Weight should have low absolute as 35 - it should not allow a value lower than 35.
- [x] In ANC encounter, add type of ANC field - with options as ANC, Extended ANC, PMSMA. Check row 20 in linked sheet:
https://docs.google.com/spreadsheets/d/1D4IubDa6qMVUG2hN4A2-endLLUfNc-uZ/edit#gid=1016841272

- [x] HBNC encounter - Baby information section - Add Date of Discharge from hospital field after weight at the time of birth. Field only to be displayed in first HBNC.
- [x] If Child Death review encounter is done, then the decision for individual to be not alive should be updated and programs should not be visible for enrollment.
- [x] Gap between first child and second child field in Family planning enrollment should show the number of months as the difference.

**Comment by Gojo-Taqi** [comment]
ETC :- 100 mins
Completed in : 99 mins

**Comment by utkarshavni** [comment]
Not fixed.
- [x] "180 Iron Folic Acid tablet issued or not" question is not visible while doing an ANC but only visible while editing it.
- [x] Whether HRP confirmed question always shows Yes as autopopulated in ANC.
- [x] More than 5 ANCs should not be scheduled for a pregnant woman unless she is high risk pregnancy.

**Comment by Dinesh2019** [comment]
Not fixed.
- [x] "180 Iron Folic Acid tablet issued or not" question is not visible while doing an ANC but only visible while editing it.  -- ( After completing the first ANC followup this question is displayed 
- [x] Whether HRP confirmed question always shows Yes as autopopulated in ANC.  we have condition if we want to have the question as No while enrolling into pregnancy for height we have to give the value as normal eg : height as 155 and in ANC weight as 55, Bp - 102 and Bp-diastolic as 58 and HB as 13

**Comment by Gojo-Taqi** [comment]
Fixed the confusions
