### ISSUE TITLE
[SAKHI] Sakhi 2.0 UAT Feedback

### ISSUE THREAD

**Issue by Gojo-Taqi** [avniproject/SAKHI#61]
UAT Org - Sakhi App UAT
Prod org - SAKHI App

Reference sheet:
https://docs.google.com/spreadsheets/d/1gzBheHfP6rQzbAnQMuz4wJr33Mo2T4EzPmvR_RT3Ba4/edit#gid=1231573446

**Individual Registration**
- [x] Bug # 75 - Keep the questions mentioned below in the sequence given.
1. Count of male children
2. Count of female children
3. Count of Other children
4. Total count of children -  Sum of values given for all the questions given above.

**Pregnancy enrollment:**
- [x] Bug# 148 - If "Are you taking any medicine for TB / BP / Diabetes / Heart disease / Kidney Disorder / Liver Disorder" answer is No, then Suspected High Risk pregnancy question should auto populate No as value in answer.
ANC form:**
- [x] Bug# 37 -
- Remove check for visibility for TD 1 Dose, TD 2 Dose and TD booster dose. The fields should be displayed always.
- If  "Tentative TD 1 Date (VHND / PMSMA)" is present in enrollment form then auto populate TD 1 dose.
- If  "Tentative TD 2 Date (VHND / PMSMA)" is present in enrollment form then auto populate TD 2 dose. 
- If  "Tentative date for booster (VHND / PMSMA)" present in enrollment. then auto populate  TD Booster dose.
**Delivery form:**
- [x] Bug # 166 - Date of Delivery cannot be before Date of Admission
- [x] Date of Discharge cannot be before Date of Delivery
- [x] Date of Death cannot be before Date of Admission
- [x] Date of Admission cannot be before Enrolment Date

**Child enrollment:**
- [x] Bug# 150 - Add the field "Status of Child" after Child RCH ID field. Data type - Coded, Options - "Active", "Migrated Out" and "Other", Single Select.
- [x] Add a field "Specify Other" if Other is selected above
**Family Planning enrollment:**
- [x] BUG# 167 Auto populate RCH ID if available in pregnancy enrolment or Program encounter of pregnancy
- [x] Bug# 169 - 2nd Child Date of birth should be either same as 1st child date of birth or it should only allow date after 9 months.
**Family Planning follow-up**
- [x] Bug# 149 -  If "Is Self verified" answer is Yes, user should not be able to fill the follow-up form again.

**Comment by vedfordev** [comment]
Estimate 2-3 hours

**Comment by vedfordev** [comment]
### Developer Notes :

---
__Bug# 148__ :

| Last pregnancy complications | Are you taking any medicine for TB / BP / Diabetes / Heart disease / Kidney Disorder / Liver Disorder | Acceptance |
| ----------- | ----------- | ----------- |
| Other than None | Yes | Yes|
| Other than None | No | Yes|
| None | Yes | Yes|
| None | No | No|
| - | Yes | Yes |
| - | No | No |


---
___Bug# 37__

Tentative TD 2 Date (VHND / PMSMA)  has default visibility as false

---

__Bug# 150__

both field should be mandatory

**Comment by Dinesh2019** [comment]
@vedfordev we have to have date validation for the date of admission in the delivery encounter

**Comment by Dinesh2019** [comment]
@vedfordev @utkarshavni we have to auto-populate the ANC 1 dose details in the  following ANC form as well

**Comment by Dinesh2019** [comment]
Test scenarios 
1. In individual registration if the age is greater than 18 and martial status is other than unmarried show the count  of male, female and other
2. In individual registration if the age is less than 18 and martial status is other than unmarried do not show the question
3. In individual registration if the age is greater than 18 and martial status is unmarried do not show the question
4. The sum of individual should be auto calculated from count of male ,female and others
5. Enter the values other number and check the the sum of individual
6. Pregnancy enrollment last pregnancy complication is other than none and are you taking 
Any medicine is yes consider as high risk
7.Pregnancy enrollment last pregnancy complication is other than none and are you taking 
Any medicine is no consider as high risk
8.Pregnancy enrollment last pregnancy complication is none and are you taking 
Any medicine is yes consider as high risk
9.Pregnancy enrollment last pregnancy complication is none and are you taking 
Any medicine is no consider as high risk
10.	•	Remove check for visibility for TD 1 Dose, TD 2 Dose and TD booster dose. The fields should be displayed always and also for ANC
* If "Tentative TD 1 Date (VHND / PMSMA)" is present in enrollment form then auto populate TD 1 dose.
* If "Tentative TD 2 Date (VHND / PMSMA)" is present in enrollment form then auto populate TD 2 dose.
* If "Tentative date for booster (VHND / PMSMA)" present in enrollment. then auto populate TD Booster dose.
11. Date of Delivery cannot be before Date of Admission
12.Date of Discharge cannot be before Date of Delivery
13.Date of Death cannot be before Date of Admission
14.child enrolment status of child question is added and it is single select
15.other than specify other 
16.Auto populate RCH ID if available in pregnancy enrolment or Program encounter of pregnanc
17.2nd Child Date of birth should be either same as 1st child date of birth or it should only allow date after 9 months.
18.2nd Child Date of birth should  be same as 1st child date of birth
19.2nd Child Date of birth should be it should only allow date after 10 months.
20.2nd Child Date of birth should be it should only allow date less than 9 months shows the error.
21.Family follow -up Is Self verified is yes should not be able to fill the follow-up form again
22.Family follow -up Is Self verified is no should be able to fill the follow-up form again

**Comment by utkarshavni** [comment]
@vedfordev 
Update - Date of Admission in Delivery form should not be in future.
